name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_amd64:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
      
      
  build_aarch64:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install cross
      run: cargo install cross --git https://github.com/cross-rs/cross
    - name: Build
      run: cross build --verbose --target aarch64-unknown-linux-gnu:latest
    - name: Run tests
      run: cross test --verbose --target aarch64-unknown-linux-gnu:latest
